osx_image: xcode8
language: objective-c
rvm: "2.2.2"

env:
  global:
    - LANG=en_US.UTF-8

cache:
  - bundler

before_install:
  - brew update
  - carthage bootstrap

script:
  - bundle exec rake test

# after_success:
#   - bash <(curl -s https://codecov.io/bash)